name: Build and Deploy glom

on:
  push:	
    branches:	
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x]

    steps:
    - name: Checkout master
      uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm install
      env:
        CI: true
    - name: npm test
      run: npm test
      env:
        CI: true
    - name: npm build
      run: npm run build --if-present
      env:
        CI: true
    #- name: Checkout master (again)
    #  uses: actions/checkout@master
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BUILD_DIR: "build/"
