name: Build and Deploy glom

on:
  push:	
    branches:	
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x]

    steps:
    - name: Checkout master
      uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm install
      env:
        CI: true
    - name: npm test
      run: npm test
      env:
        CI: true
    #- name: Checkout master (again)
    #  uses: actions/checkout@master
    - name: GH Pages deploy
      uses: Cecilapp/GitHub-Pages-deploy@1.1.0
      env:
        # GH_TOKEN: ${{ secrets.GH_TOKEN }}
        BUILD_DIR: "build/"
        EMAIL: milo@milogert.com
